bin/attach: convert to bash script

diff --git a/bin/attach b/bin/attach
--- a/bin/attach
+++ b/bin/attach
@@ -1,30 +1,31 @@
-#!/usr/bin/env fish
-if test (count $argv) -gt 1
-    echo "usage: attach [SESSION]"
-    exit 2
-end
+#!/usr/bin/env bash
+set -e
 
-if test "$TMUX"
-    echo "error: already attached to a tmux session"
-    exit 2
-end
+prog="$(basename $0)"
 
-if test "$argv[1]"
-    set session "$argv[1]"
-else
-    set session "main"
-end
+if [[ "$#" -gt 1 ]]; then
+    echo "usage: $prog [SESSION]" >&2
+    exit 2
+fi
+session="${1:-main}"
+
+if [[ -n "$TMUX" ]]; then
+    echo 'error: already attached to a tmux session'
+    exit 2
+fi
 
 # set up symlink to ssh-agent socket
-if test -n "$SSH_AUTH_SOCK"
-    ln -sfn $SSH_AUTH_SOCK ~/.ssh_auth_sock_$session
-end
+if [[ -n "$SSH_AUTH_SOCK" ]]; then
+    ln -sfn "$SSH_AUTH_SOCK" "$HOME/.ssh_auth_sock_$session"
+fi
 
-if not tmux ls -F '#S' ^/dev/null | grep -q $session
-    tmux new-session -d -s $session
+if ! tmux ls -F '#S' 2>/dev/null | grep -q "$session"; then
+    tmux new-session -d -s "$session"
     # create extra windows and set default layouts here
-end
-tmux attach-session -d -t $session
-if test -e ~/.ssh_auth_sock_$session
-    rm ~/.ssh_auth_sock_$session
-end
+fi
+
+tmux attach-session -d -t "$session"
+
+if [[ -e "$HOME/.ssh_auth_sock_$session" ]]; then
+    rm "$HOME/.ssh_auth_sock_$session"
+fi
